### ISSUE TITLE
i got this error after run Market Feed Usage code

### ISSUE THREAD

**Issue by sandipawar** [dhan-oss/DhanHQ-py#29]
Subscription code : 15
C:\Program Files\Python311\Lib\site-packages\dhanhq\marketfeed.py:79: RuntimeWarning: coroutine 'DhanFeed.connect' was never awaited
  self.connect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "D:\Trading\Sandip Trading Setup\Dhan FUT\Dhan.py", line 36, in <module>
    feed.run_forever()
  File "C:\Program Files\Python311\Lib\site-packages\dhanhq\marketfeed.py", line 83, in run_forever
    self.loop.run_until_complete(self.connect())
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\dhanhq\marketfeed.py", line 88, in connect
    self.ws = await websockets.connect(WSS_URL)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\websockets\client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1132, in _create_connection_transport
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\websockets\client.py", line 69, in __init__
    super().__init__(**kwargs)
  File "C:\Program Files\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by sandipawar** [comment]
C:\Program Files\Python311\Lib\site-packages\dhanhq\marketfeed.py:79: RuntimeWarning: coroutine 'DhanFeed.connect' was never awaited
  self.connect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by dhan-oss** [comment]
Hey @sandipawar 

We are fixing this in the next version of library, where this warning will not appear.

> Lock.init() got an unexpected keyword argument 'loop'

This will not appear if the usage code is added, can you check code once at your end.

**Comment by sandipawar** [comment]
"This will not appear if the usage code is added, can you check code once at your end."  How to add usage code ?

**Comment by dhan-oss** [comment]
Hello @sandipawar 

We just released a new version to the library v1.3.2 - Optimising `marketfeed` module.
This solves for the highlighted issue.
